repos:
  - repo: local
    hooks:
      - id: oxfmt
        alias: check-oxfmt
        name: check-oxfmt
        entry: oxfmt
        args: ["--write", "--no-error-on-unmatched-pattern"]
        language: node
        additional_dependencies: ["oxfmt@0.40.0"]
        types_or: [markdown, json, yaml]
  - repo: https://github.com/ComPWA/mirrors-taplo
    rev: v0.9.3
    hooks:
      - id: taplo-format
        alias: check-taplo
        name: check-taplo
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.11
    hooks:
      - id: actionlint
        alias: check-actionlint
        name: check-actionlint
